name: Node CI

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up jet.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: deploy
        run: echo "deploy to server"

